server:
  port: 8083
spring:
  data:
    solr:
      host: http://192.168.230.128:8080/solr
image:
  path: http://192.168.230.128/
dubbo:
  application:
    name: shop_search
  registry:
    address: 192.168.230.128
    protocol: zookeeper
    port: 2181
  consumer:
    check: false
    retries: 10
    timeout: 10000