server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource

mybatis:
  mapper-locations: classpath*:com/qf/dao/mapper/*.xml
  type-aliases-package: com.qf.entity
dubbo:
  application:
    name: shop_service_provider
  registry:
    address: zookeeper://192.168.230.128:2181
  protocol:
    name: dubbo
    port: 20880
